// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOIGX7BM2EXIyDZ_nQLtwIwt420F-LqMg',
    appId: '1:432592182961:web:9bef7468d695df369c4c90',
    messagingSenderId: '432592182961',
    projectId: 'neuyklm',
    authDomain: 'neuyklm.firebaseapp.com',
    storageBucket: 'neuyklm.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBfKc73mPgoBAHTepwTpVqVxBcpuAOb6GE',
    appId: '1:432592182961:android:129c2e5f13f347d99c4c90',
    messagingSenderId: '432592182961',
    projectId: 'neuyklm',
    storageBucket: 'neuyklm.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzaF8iP150lWGNmR3QcaLWiV4JiEfG_oU',
    appId: '1:432592182961:ios:9400d8939a53a1f49c4c90',
    messagingSenderId: '432592182961',
    projectId: 'neuyklm',
    storageBucket: 'neuyklm.firebasestorage.app',
    iosBundleId: 'com.example.qrYoklamaWeb',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzaF8iP150lWGNmR3QcaLWiV4JiEfG_oU',
    appId: '1:432592182961:ios:9400d8939a53a1f49c4c90',
    messagingSenderId: '432592182961',
    projectId: 'neuyklm',
    storageBucket: 'neuyklm.firebasestorage.app',
    iosBundleId: 'com.example.qrYoklamaWeb',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOIGX7BM2EXIyDZ_nQLtwIwt420F-LqMg',
    appId: '1:432592182961:web:92f2b1d1633b3adf9c4c90',
    messagingSenderId: '432592182961',
    projectId: 'neuyklm',
    authDomain: 'neuyklm.firebaseapp.com',
    storageBucket: 'neuyklm.firebasestorage.app',
  );

}